### ISSUE TITLE
Implementing CRUD samples

### ISSUE THREAD

**Issue by naoharu** [toshi-nao/web-app-sample#4]
# Background
- Create sample CRUD process to DB when using go gin and mongo
# What to Implement
- Input information from the screen using vue.js, send HTTP Request, and CRUD on the server side
# Points to consider
### HTTP request sample
```
$ curl --location --request PUT  'localhost:8080/api/tutorials/' \                        
--header 'Content-Type: text/plain' \
--data '{
    "description": "Insert new data",      
    "title": "new",            
    "published": false
}'
```
### What if there are identical PKs?
Handling methods need to be considered

## Read
- Do we have to make just findAll() only? or make a findById() too?
## Update
- Update needs to specify the update target with a byId-like thing. should it be Insert if it doesn't exist in byId? (i.e. should it be an Upsert method?) Or 404?
   - No, it should return an error message such as "The tutorial has already been deleted."

### HTTP request sample
```
curl --location --request POST 'localhost:8080/api/tutorials/64b0ae25c5998cbb3c6904f9' \
--header 'Content-Type: text/plain' \
--data '{
    "description": "updated Description 2",
    "title": "updated Title 2",
    "published": false
}'
```
The `:id` in `/api/tutorials/:id`may need to be changed based on the `_id` in the MongoDB document. Try `db.tutorial_collection.find()` with MongoDB Shell to see the document `_id`s.

## Delete
- should it be 200 or 404 if delete target does not exit?
  - it will be 404 same as other methods

### HTTP request sample
```
curl --location --request DELETE 'localhost:8080/api/tutorials/64b0ae25c5998cbb3c6904f9' 
```

# Sub-tasks

- [x] Create @naoharu 
- [x] Read
- [x] Update @toshihue 
- [x] Delete @naoharu 
- [x] What is `defer cancel()` https://github.com/toshi-nao/web-app-sample/blob/main/go-gin/controllers/tutorial_controller.go#L78
- [x] Should we use `c *gin.Context` for the collection methods? https://github.com/toshi-nao/web-app-sample/blob/main/go-gin/controllers/tutorial_controller.go#L78
- [ ] Deleting `id string` may affect Vue.js side.

**Comment by naoharu** [comment]
Reopen because [merged PR ](https://github.com/toshi-nao/web-app-sample/pull/11) closed this issue.

**Comment by naoharu** [comment]
> What if there are identical PKs?
> Handling methods need to be considered

When creating with WebAPI, PK collision does not occur because PK is not specified explicitly but is issued automatically on the back end side.

**Comment by naoharu** [comment]
I briefly looked up `defer cancel()`.
This article has more details about defer.
https://qiita.com/Ishidall/items/8dd663de5755a15e84f2
It seems that defer is a declaration of deferred execution that is executed after the function it contains returns.
So, `defer cancel()` means that `cancel()` will be executed after the CRUD methods return in this case.
